### ISSUE TITLE
Issue with SCSS interpolation

### ISSUE THREAD

**Issue by MarcelGerber** [codemirror/CodeMirror#3133]
(adobe/brackets#10747)

1. Go to http://codemirror.net/mode/css/scss.html
2. Paste this stylesheet:
``` SCSS
.foo {
  height: calc(#{em($link-height)} + 1px);
  width: 1px;
}
```

Result:
`width` is green (`.cm-tag`).

Expected:
`width` is black (`.cm-property`).

Apparently, the issue happens every time there's an interpolation inside a function you can also repro with a simple `calc(#{});`.
