### ISSUE TITLE
Add focus CSS

### ISSUE THREAD

**Issue by JasonBarnabe** [codemirror/CodeMirror#3187]
When you focus a CodeMirror instance, it should have the same effect as a focused textarea. With Chrome at least, the CSS to accomplish this is:

```css
.CodeMirror-focused {
  outline: auto 5px -webkit-focus-ring-color;
  outline-offset: 0;
}
```
http://trac.webkit.org/browser/trunk/Source/WebCore/css/html.css#L1102
http://trac.webkit.org/browser/trunk/Source/WebCore/css/html.css#L1119
