### ISSUE TITLE
[scss] Inline interpolation: Functions marked as error

### ISSUE THREAD

**Issue by MarcelGerber** [codemirror/CodeMirror#3253]
1. Go to http://codemirror.net/mode/css/scss.html
2. Paste this stylesheet:
``` scss
.foo {
  height: calc(#{em($link-height)} + 1px);
  width: 1px;
}
```

Result:
The parens are marked as "error".
