### ISSUE TITLE
CSS: Better @supports syntax highlighting support for colors

### ISSUE THREAD

**Issue by JosephPecoraro** [codemirror/CodeMirror#3336]
CodeMirror should syntax highlight the "property: value" inside the @supports condition as well as "and", "or" and "not" keywords.

MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/@supports
Spec: http://dev.w3.org/csswg/css-conditional-3/
Grammar: http://dev.w3.org/csswg/css-conditional-3/#at-supports

Example:

```css
@supports ( (color: red) or (color: blue) ) {
    p { color: red; }
}
```

The @supports syntax is supported in Chrome, Firefox, and WebKit nightlies.
