### ISSUE TITLE
Impossible to reset ::selection color to browser default

### ISSUE THREAD

**Issue by sgoo** [codemirror/CodeMirror#3342]
In 5.0 a style was added to change the color of `::selection` in e3748a29e86d6bcfea21e726319b770ef1a38ecb. This style affects everything inside `.CodeMirror` including widgets and is impossible to reset back to the browser default (because each Browser/OS combination has a different value).

If there isn't a way to keep a nice selection style on the content editable input without the `::selection` style would it be possible to make this style more specific so that it only touches `.CodeMirror pre` and not line widgets.

**Comment by marijnh** [comment]
This is a good point, but your solution doesn't work for inline (`markText`) widgets, which will end up _inside_ the `pre` tag. Not sure what to do about that. Does modern CSS allow any kind of negative selectors yet? ('When not inside class X')

**Comment by sgoo** [comment]
There is the `:not()` selector, so I guess the style could be updated to something like this?
```css
.CodeMirror:not(.CodeMirror-browser-select) ::selection { background: #d7d4f0; }
```

So people can set the `CodeMirror-browser-select` class on the `.CodeMirror` if they want to keep the default browser `::selection`.

**Comment by marijnh** [comment]
That's not a great solution either, I think. I modified CodeMirror to give the wrapping span for each line a `CodeMirror-line` class, and then changed the selectors like this:

```css
.CodeMirror-line::selection, .CodeMirror-line > span::selection { background: #d7d4f0; }
.CodeMirror-line::-moz-selection, .CodeMirror-line > span::-moz-selection { background: #d7d4f0; }
```

It works (at least on FF and Chrome). Does it look sane to you?
