### ISSUE TITLE
Proof of concept styling: Pages like editor with centered fixed-width editing zone, v-scroll next to right window border

### ISSUE THREAD

**Issue by baoshan** [codemirror/CodeMirror#3483]
A sketch may help conveying my idea:

![canvas_like_editor](https://cloud.githubusercontent.com/assets/1096182/9485683/bbaffa9a-4bef-11e5-9f9e-c58dd6fc6edc.png)

The best I can get is:

```css
.CodeMirror {
  width: 100%;
  height : 100%;
}

  .CodeMirror-lines {
    margin-top: 3em;
    padding-top: 3em;
    border: 1px solid black;
  }

div.CodeMirror-sizer {
  width: 816px;
  margin: 0 auto !important;
}

```

But the `selected` lines have wrong width set:

![selected_line](https://cloud.githubusercontent.com/assets/1096182/9485755/d8db712a-4bf0-11e5-8f8e-2ff35d40cee1.png)

Any suggestions? And should I always have the `!important` hack?

Thanks anyway.

**Comment by baoshan** [comment]
It seems the `simplescroll` addon is a good solution.
Can I use `native` scroll bar for the desired layout?

Thanks @marijnh .

**Comment by marijnh** [comment]
This is simply not supported. You can add vertical padding to `.CodeMirror-lines` and horizontal to `.CodeMirror pre`, but I don't think there's a way to get a border around the content. I'm not sure how the simplescroll addon would help here.

**Comment by baoshan** [comment]
I tried:

```css
.CodeMirror-simplescroll-vertical
{
  position   : fixed;
  right      : 0;
}

.CodeMirror-lines {
  /* or apply a border */
  box-shadow  : 0px 0px 3px rgba(0,0,0,.3);
}


```

And it looks fine.

One thing left unsolved: I can only scroll in the editor zone, not the whitespace around them.

Any trap in the above snippet?
