### ISSUE TITLE
[css mode] Support CSS4 #rrggbbaa and #rgba colors

### ISSUE THREAD

**Issue by JosephPecoraro** [codemirror/CodeMirror#3625]
Support CSS4 `#rrggbbaa` and `#rgba` colors. Hex with alpha.

Currently the css mode treats these as errors.

```css
body {
  color: #F00;
  color: #F00F;
  color: #FF0000;
  color: #FF0000FF;
}
```

[WebKit supports](http://trac.webkit.org/changeset/192023) them. I don't think Firefox or Chrome do at the moment. [Specification](https://drafts.csswg.org/css-color/#hex-notation) is still a draft, but I don't think there is anything controversial about this.
