### ISSUE TITLE
Custom Font Does Not Work

### ISSUE THREAD

**Issue by niftylettuce** [codemirror/CodeMirror#3764]
The line height and cursor positioning, and selection is all off

All I did was add this CSS, it's not documented anywhere how to fix this...?

```css
.CodeMirror {
  font-family: Inconsolata, monospace;
}
```

![screen shot 2016-01-14 at 1 24 09 am](https://cloud.githubusercontent.com/assets/523141/12317743/1365f45c-ba62-11e5-89f3-240bb57fa9fa.png)
![screen shot 2016-01-14 at 1 24 03 am](https://cloud.githubusercontent.com/assets/523141/12317744/136c5d9c-ba62-11e5-8b47-b6210762d797.png)
