### ISSUE TITLE
Uncaught ReferenceError: diff_match_patch is not defined

### ISSUE THREAD

**Issue by anton-aleksandrov** [codemirror/CodeMirror#4059]
I'm getting this error:
```
Uncaught ReferenceError: diff_match_patch is not defined
```

Here is the bundle i use:
```
/* CodeMirror - Minified & Bundled
   Generated on 6/8/2016 with http://codemirror.net/doc/compress.html
   Version: HEAD

   CodeMirror Library:
   - codemirror.js
   Modes:
   - markdown.js
   Add-ons:
   - merge.js
 */
```
