### ISSUE TITLE
CSS conflict with reveal.js

### ISSUE THREAD

**Issue by viebel** [codemirror/CodeMirror#4189]
I'm trying to have codemirror on my slides with reveal.js and there seems to be a css conflict.

Look at this page that reproduces the issue: http://viebel.github.io/klipse/misc/reveal-codemirror.html.

There are a couple of issues:

1. The code is centered instead of aligned left
2. When trying to navigate the code with the keyboard arrows, it feels very weird
3. The cursor is not visible when editing the code

**Comment by tan31989** [comment]
You would have to override the css for CodeMirror, because reveal css will change/modify the properties of div's and so on.

What you would have to alter is as follows:

```css
.reveal .CodeMirror-lines {
    text-align: left !important;
    ......
    ......
}
```
Alter the CSS for getting the result, because, your CodeMirror is inside a reveal div and that will obviously add it's own css, like:
```css
.reveal .slides {
    position: absolute;
    width: 100%;
    height: 100%;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    margin: auto;
    overflow: visible;
    z-index: 1;
    text-align: center;  /* Culprit -- changing the alignment */
    -webkit-perspective: 600px;
    perspective: 600px;
    -webkit-perspective-origin: 50% 40%;
    perspective-origin: 50% 40%;
}
```
