### ISSUE TITLE
Theme "pastel-on-dark" should not specify an absolute font size

### ISSUE THREAD

**Issue by danieleds** [codemirror/CodeMirror#4206]
In `pastel-on-dark.css` we have this:

```css
.cm-s-pastel-on-dark.CodeMirror {
	background: #2c2827;
	color: #8F938F;
	line-height: 1.5;
	font-size: 14px;
}
```

The font size should not be absolute. It should use a relative unit, as in `liquibyte.css`.
