### ISSUE TITLE
[css mode] Inconsistent syntax highlighting for non-lowercase css value functions (translate() vs translateX())

### ISSUE THREAD

**Issue by JosephPecoraro** [codemirror/CodeMirror#4325]
Inconsistent syntax highlighting for non-lowercase css value functions:

Paste the following in the [css mode](https://codemirror.net/mode/css/index.html) editor:

```css
body {
  transform: translate(10px);
  transform: translateX(10px);
}
```

Expected: `translate` and `translateX` to highlight the same way (`m-atom`), however they currently highlight differently.

**Comment by JosephPecoraro** [comment]
In `css.js` there is:

```javascript
  function wordAsValue(stream) {
    var word = stream.current().toLowerCase();
    if (valueKeywords.hasOwnProperty(word))
      override = "atom";
    ...
  }
```

Which checks for lower cased property names in `valueKeywords`. However `valueKeywords` doesn't contain lowercased property names. In this case it would contain `translateX` but not `translatex`.

However, we do want to canonicalize in some way when checking keywords, because value keywords are not always case-sensitive. For example both of these should (and do) highlight the same way (in CodeMirror):

```css
body {
    font-style: italic;
    font-style: ITALIC;
}
```
