### ISSUE TITLE
CSS & SCSS mode: psuedo element/classes and vendor prefix

### ISSUE THREAD

**Issue by ficristo** [codemirror/CodeMirror#4585]
In CSS & SCSS mode the psuedo elements/classes are parsed as `variable-3`.
But if they are prefixed with a browser vendor they are parsed as `meta` for the prefix (which is expected) and `tag` for the rest: shouldn't be parsed as `variable-3`?
```css
/* -webkit- is meta, input-placeholder is tag */
*::-webkit-input-placeholder {
  color: #666;
}
/* -moz- is meta, placeholder is tag */
*:-moz-placeholder {
  opacity: 1px;
}
/* after is variable-3 */
input:after {
  content: ""
}
```
