### ISSUE TITLE
Improve readability of highlighted matching brackets

### ISSUE THREAD

**Issue by dlukes** [codemirror/CodeMirror#5063]
CodeMirror's default theme is great and very readable -- except for matching brackets, which get highlighted in a light green color and become hard to see, especially on projectors, but even on a regular monitor. This is the bit of CSS in question:

https://github.com/codemirror/CodeMirror/blob/ad6635a5b40b20cc3f7ca9a77ef1b42634597790/lib/codemirror.css#L148

Many of the alternative themes display an outline around matching brackets instead. Would you be open to considering changing the default theme to use an outline as well? Something along the lines of:

```css
div.CodeMirror span.CodeMirror-matchingbracket {
        outline: 1px solid #bbb;
}
```

Or perhaps just a different color with a better contrast -- anything that would improve the readability, really :)
