### ISSUE TITLE
Cannot use "Select All" on iOS

### ISSUE THREAD

**Issue by louisatome** [codemirror/CodeMirror#5073]
When I try to use the "Select All" button from the long-press contextual menu on iOS, the cursor goes to the end of my script but my text isn't selected.
The problem appears in the version 5.25.0.
If you want to try it : 
- Fiddle with version 5.24.0 when it worked : https://jsfiddle.net/az1ke5zz/3/
- Fiddle with version 5.25.0 when it doesn't work anymore : https://jsfiddle.net/az1ke5zz/4/

After some deeper research, it looks like the commit that broke the functionality is  1d00df9e9e6ced8516a3400e3f4bdb8147ab514d and more specifically the removal of the following CSS : 
```css
.CodeMirror-gutter-wrapper {
  -webkit-user-select: none;
  -moz-user-select: none;
  user-select: none;
}
```
What was the reason for removing it ?
