### ISSUE TITLE
.cm-type style not applied on "type" tokens

### ISSUE THREAD

**Issue by vinklein** [codemirror/CodeMirror#5103]
In codemirror.css and many other css file under `theme` directory there is a ',' missing before `.cm-type`.
.cm-s-default .cm-variable-3, .cm-s-default .cm-type {color: #085;}
Therefore syntax highlightning won't work on "type" tokens.

**Comment by marijnh** [comment]
The line I'm seeing is:

```css
.cm-s-default .cm-variable-3, .cm-s-default .cm-type {color: #085;}
```

Which looks valid. Why do you think there's a missing comma?
