### ISSUE TITLE
YAML lint errors are not displayed

### ISSUE THREAD

**Issue by liorbentov** [codemirror/CodeMirror#5143]
Hey, this is options object:
```
  mode: "yaml",
  readOnly: false,
  lineNumbers: true,
  lineWrapping: true,
  lint: true,
  foldGutter: true,
  gutters: [
    "CodeMirror-linenumbers",
    "CodeMirror-lint-markers",
    "CodeMirror-foldgutter"
  ]
```

And that's the YAML:
```
---
  users:
    tj:
      name: tj
      age: 23
      email: 'tj@vision-media.ca'
    bob:
      name: 'bob'
      age: 27
    ted: { name: ted, age: 32, email: ted@tedtalks.com }
  country:
    name: Österreich
    website: http://en.wikipedia.org/wiki/Austria
  space:
    description: space, the final frontier
  brackets:
    square: Square [brackets] can go in the middle of strings
    squiggle: Squiggle {brackets} can also go in the middle of strings!
    extrasquare: [Scratch that] brackets can go at the beginning as long as they close and have text after.
    extrasquiggle: {Scratch that} squigs can go at the beginning also!
```

Now, I'm sure there is an error, and it also gets into to yaml-lint.js and catches the error, but for some reason, it's not being displayed...

Would love any help on this.
Thanks!
