### ISSUE TITLE
CSS Mode - support for 'mix-blend-mode' property

### ISSUE THREAD

**Issue by curran** [codemirror/CodeMirror#5625]
The [valid CSS property `mix-blend-mode`](https://developer.mozilla.org/en-US/docs/Web/CSS/mix-blend-mode) appears not to be recognized by CodeMirror's CSS mode.

![image](https://user-images.githubusercontent.com/68416/47153783-30f9bf00-d2fe-11e8-8e87-ac05eb453234.png)

To reproduce the issue, the following can be pasted into the CSS demo https://codemirror.net/mode/css/

```css
.some-svg-shape {
  fill: red; /* Example of how mix-blend-mode should appear. */
  mix-blend-mode: darken; /* The property is highlighted as invalid. */
}
```
