### ISSUE TITLE
Is it safe to style vscrollbar, or should we use the simplescrollbars addon?

### ISSUE THREAD

**Issue by vincentwoo** [codemirror/CodeMirror#5807]
I'm having an issue with a custom styled scrollbar appearing over CodeMirror contents:

![image](https://user-images.githubusercontent.com/613320/54329162-c5c2c900-45cd-11e9-862e-32441fb6cab1.png)

The somewhat mysterious thing is this goes away if I plug a mouse into my computer. I am running OSX + Chrome. I think this is because OSX wants to always render the native scrollbar with a mouse plugged in.

Anyway, I was wondering if our styling of vscrollbar is allowed:

```scss
.CodeMirror-vscrollbar {
  margin-right: 10px;
  &::-webkit-scrollbar {
    width: 8px; /* 1px wider than Lion. */
    /* This is more usable for users trying to click it. */
    -webkit-border-radius: 100px;
  }

  /* The scrollbar 'thumb' ...that marque oval shape in a scrollbar */
  &::-webkit-scrollbar-thumb:vertical {
    -webkit-border-radius: 100px;
  }
  &::-webkit-scrollbar-thumb:vertical:active {
    -webkit-border-radius: 100px;
  }
}
```

This makes the vscrollbar element wider than it would otherwise be, and I wonder if this is contributing to the CodeMirror-sizer being unable to realize it should be a bit smaller on the right-hand side. Should we be using the scrollbars addon in this case, too?
