### ISSUE TITLE
difficulties styling cursor, selection using CSS as per docs

### ISSUE THREAD

**Issue by loveencounterflow** [codemirror/CodeMirror#5847]
In contradiction to what the documentation states, I find myself unable to style the appearances of the cursor and the selection highlighting. At first I tried this using my own stylesheet to no avail; I then loaded some themes and started tinkering with the settings in those CSS files. For example, in `theme/mdn-like.css` I can change the colors in the following rules:

```css
.cm-s-mdn-like.CodeMirror { color: #999; background-color: #fff; }
.cm-s-mdn-like div.CodeMirror-selected { background: #cfc; }
.cm-s-mdn-like .CodeMirror-cursor { border-left: 2px solid #222; }
```
but all I get to see is the editor background color being changed (so at least I know I'm not editing the wrong file). However what *does* change the selection color is this rule (also taken from `mdn-like.css`):

```css
.CodeMirror-line::selection,
.CodeMirror-line > span::selection,
.CodeMirror-line > span > span::selection {
	background: orange !important; }
``` 

It does look like the `.cm-s-mdn-like div.CodeMirror-selected` rule is superfluous (or only there for backwards compatibility?). In any case I searched quite a while for this so I guess it'd be worth pointing out in the documentation.

As for the cursor/caret, it's always 1px wide (and takes on the color of the neighboring text?). This is also true for the `mdn-like` stylesheet which mandates a cursor 2px wide—at least when I create the CodeMirror instance with `inputStyle: 'textarea'` instead of `contenteditable`. IOW caret styles only work with text areas. All you can do in the latter mode of operation is using the `caret-color` CSS property as per https://developer.mozilla.org/en-US/docs/Web/CSS/caret-color. 

Finding this out was considerable more difficult than I first thought, so maybe this issue can fulfill its purpose in answering the questions of some future user...

And thanks for this great editor, Marijn!
