### ISSUE TITLE
cannot enable CSS parameter.

### ISSUE THREAD

**Issue by Daru-IBN5100** [codemirror/CodeMirror#6005]
CodeMirror v.5.48 Chrome OS v.76.0.3809.136 stable
Japanese and input-style contenteditable with Search Addon

"Selected color" and "Find current selection color" cannot enable CSS parameter.

It is correctly enabled when "inputStyle: textarea" mode.

Thank you for the wonderful Lib.

**Comment by marijnh** [comment]
> "Selected color" and "Find current selection color" cannot enable CSS parameter.

I have no idea what these are, and what enabling CSS parameter would mean.

**Comment by Daru-IBN5100** [comment]
I think , I have no choice The color is default in "inputStyle: 'contenteditable'" mode. probably due to content element limitations.
However, I would be happy if the selection cursor position in the search add-on can be expressed as an alternative.

e.g. Attached image file CSS parameter is
.CodeMirror-cursor {border-left: 2px solid #00FF00 !important;}
.CodeMirror-selected {background-color: #FF000088 !important;}

![cm_issue](https://user-images.githubusercontent.com/54938701/65132269-a785cc00-da3b-11e9-837d-ffe1e458bf7c.png)

**Comment by marijnh** [comment]
The search box is just an `<input>` element, not a CodeMirror instance, so styles like `.CodeMirror-cursor` will definitely not affect it.

**Comment by Daru-IBN5100** [comment]
The part I want to fix is "Find current selection color", it is not "search box".

Thanks.
![cm_issue_a](https://user-images.githubusercontent.com/54938701/65134437-42cc7080-da3f-11e9-96b6-1e047a474e48.png)

**Comment by marijnh** [comment]
That's just a selection. So this doesn't really have anything to do with search at all?

You can style the native selection on most platforms with rules like this

```css
.CodeMirror-line::selection, .CodeMirror-line > span::selection, .CodeMirror-line > span > span::selection { background: #d7d4f0; }
.CodeMirror-line::-moz-selection, .CodeMirror-line > span::-moz-selection, .CodeMirror-line > span > span::-moz-selection { background: #d7d4f0; } /* Firefox */
```
The [caret-color](https://developer.mozilla.org/en-US/docs/Web/CSS/caret-color) css property can change the cursor color, but doesn't work on IE/Edge.
