### ISSUE TITLE
Textarea visibility hidden breaks CodeMirror

### ISSUE THREAD

**Issue by erosman** [codemirror/CodeMirror#6557]
CodeMirror 5.58.3

I wanted to hide the textarea (it shows before CM is started).

```css
teaxtarea {
  visibility: visible;
}
```

With above the codeMirror editor appears fine but it is no longer editable.

Is that the expected behaviour? :thinking:

I had to use the following instead:

```css
textarea {
  background-color: transparent;
  color: transparent;
  border: 0;
  resize: none;
}
```
